use strum::{Display, VariantArray, VariantNames};
use wotw_seedgen_derive::FromStr;

/// An input action
///
/// Mirrors https://github.com/ori-community/wotw-rando-client/blob/v5/src/Core/enums/actions.h
#[derive(Debug, Clone, Copy, PartialEq, Eq, Display, FromStr, VariantNames, VariantArray)]
pub enum InputAction {
    MainMenuSaveCopy,
    MainMenuSaveDelete,
    Interact,
    Jump,
    Ability1,
    Ability2,
    Ability3,
    Glide,
    Grab,
    Dash,
    Burrow,
    Bash,
    Grapple,
    DialogueAdvance,
    DialogueOption1,
    DialogueOption2,
    DialogueOption3,
    DialogueExit,
    OpenMapsShardsInventory,
    OpenAreaMap,
    OpenInventory,
    OpenWorldMap,
    OpenShards,
    OpenWeaponWheel,
    PauseScreen,
    LiveSignIn,
    MapZoomIn,
    MapZoomOut,
    MenuSelect,
    MenuBack,
    MenuClose,
    MenuDown,
    MenuUp,
    MenuLeft,
    MenuRight,
    MenuPageLeft,
    MenuPageRight,
    LeaderboardCycleFilter,
    MapFilter,
    MapDetails,
    MapFocusOri,
    MapFocusObjective,
    Left,
    Right,
    Up,
    Down,
    OpenRandomizerWheel,
    QuickBuy,
    Binding1,
    Binding2,
    Binding3,
    Binding4,
    Binding5,
    ReconnectToServer,
    ReloadSeed,
    ShowSeedTags,
    ShowRecentPickups,
    ShowProgressWithHints,
    ToggleCursorLock,
    ToggleDebug,
    ToggleBingoBoardOverlay,
}
