use std::{
    cmp::Ordering,
    fmt::{self, Display},
    iter,
};

use crate::{
    assets::{LocDataEntry, StateDataEntry},
    Difficulty, PartialThen, Position, Shard, Skill, Teleporter, Trick, UberIdentifier, Zone,
};
use itertools::Itertools;
use rustc_hash::FxHashMap;
use serde::Serialize;
use smallvec::SmallVec;
use strum::{Display, EnumIs, EnumString, EnumTryAs};
use utoipa::ToSchema;

pub type EntranceId = i32;

#[derive(Debug, Clone, PartialEq, Serialize, ToSchema)]
pub struct Graph {
    pub nodes: Vec<Node>,
    pub default_entrance_connections: FxHashMap<EntranceId, EntranceId>,
}

impl Graph {
    // TODO use more in tests
    pub fn empty() -> Self {
        Self {
            nodes: Vec::new(),
            default_entrance_connections: FxHashMap::default(),
        }
    }

    // TODO could optimize based on the node kind we're looking for? The tag should be faster to compare than our long strings
    pub fn find_node(&self, node: &str) -> Result<usize, String> {
        self.nodes
            .iter()
            .position(|n| n.identifier() == node)
            .ok_or_else(|| format!("node \"{node}\" not found"))
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, ToSchema, EnumIs, EnumTryAs)]
pub enum Node {
    Anchor(Anchor),
    Pickup(LocDataEntry),
    State(StateDataEntry),
    LogicalState(String),
}

impl Node {
    pub fn identifier(&self) -> &str {
        match self {
            Node::Anchor(anchor) => &anchor.identifier,
            Node::Pickup(pickup) => &pickup.identifier,
            Node::State(state) => &state.identifier,
            Node::LogicalState(identifier) => identifier,
        }
    }

    pub fn zone(&self) -> Option<Zone> {
        match self {
            Node::Pickup(pickup) => Some(pickup.zone),
            _ => None,
        }
    }

    // TODO check which of these ended up being used
    pub fn uber_identifier(&self) -> Option<UberIdentifier> {
        match self {
            Node::Anchor(_) | Node::LogicalState(_) => None,
            Node::Pickup(pickup) => Some(pickup.uber_identifier),
            Node::State(state) => Some(state.uber_identifier),
        }
    }

    pub fn value(&self) -> Option<i32> {
        match self {
            Node::Anchor(_) | Node::LogicalState(_) => None,
            Node::Pickup(pickup) => pickup.value,
            Node::State(state) => state.value,
        }
    }

    pub fn position(&self) -> Option<&Position> {
        match self {
            Node::Anchor(anchor) => anchor.position.as_ref(),
            Node::Pickup(pickup) => pickup.position.as_ref(),
            Node::State(_) | Node::LogicalState(_) => None,
        }
    }

    pub fn map_position(&self) -> Option<&Position> {
        match self {
            Node::Anchor(anchor) => anchor.position.as_ref(),
            Node::Pickup(pickup) => pickup.map_position.as_ref(),
            Node::State(_) | Node::LogicalState(_) => None,
        }
    }

    pub fn can_spawn(&self) -> bool {
        match self {
            Node::Anchor(anchor) => anchor.can_spawn(),
            _ => false,
        }
    }

    pub fn expect_anchor(&self) -> &Anchor {
        match self {
            Node::Anchor(anchor) => anchor,
            _ => panic!("Called expect_anchor on {self:?}"),
        }
    }

    pub fn expect_anchor_mut(&mut self) -> &mut Anchor {
        match self {
            Node::Anchor(anchor) => anchor,
            _ => panic!("Called expect_anchor_mut on {self:?}"),
        }
    }
}

#[derive(Debug, Clone, Serialize, ToSchema)]
pub struct Anchor {
    pub identifier: String,
    pub position: Option<Position>,
    pub entrance: Option<Entrance>,
    pub can_spawn: bool,
    pub teleport_restriction: Requirement,
    pub refills: Vec<Refill>,
    pub connections: Vec<Connection>,
}

impl Anchor {
    pub fn new(identifier: String, connections: Vec<Connection>) -> Self {
        Self {
            identifier,
            position: None,
            entrance: None,
            can_spawn: true,
            teleport_restriction: Requirement::Free,
            refills: vec![],
            connections,
        }
    }

    pub fn can_spawn(&self) -> bool {
        self.position.is_some() && self.can_spawn
    }
}

impl PartialEq for Anchor {
    fn eq(&self, other: &Self) -> bool {
        self.identifier == other.identifier
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, ToSchema)]
pub struct Entrance {
    pub id: EntranceId,
    pub target: String,
    pub requirement: Requirement,
}

#[derive(Debug, Clone, PartialEq, Serialize, ToSchema)]
pub struct Connection {
    pub to: usize,
    pub requirement: Requirement,
    /// Whether this connection was implicitly generated by seedgen, e.g. entrance connections
    pub implicitly_generated: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, ToSchema)]
pub struct Refill {
    pub value: RefillValue,
    pub requirement: Requirement,
}

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Display, ToSchema)]
pub enum RefillValue {
    Full,
    Checkpoint,
    #[strum(to_string = "Health={0}")]
    Health(f32),
    #[strum(to_string = "Energy={0}")]
    Energy(f32),
}

#[derive(Debug, Clone, PartialEq, Serialize, ToSchema)]
pub enum Requirement {
    Free,
    Impossible,
    Difficulty(Difficulty),
    NormalGameDifficulty,
    Trick(Trick),
    Skill(Skill),
    EnergySkill(Skill, f32),
    NonConsumingEnergySkill(Skill),
    // TODO resources as i32?
    SpiritLight(usize),
    GorlekOre(usize),
    Keystone(usize),
    Shard(Shard),
    Teleporter(Teleporter),
    Water,
    State(usize),
    Damage(f32),
    Danger(f32),
    // utoipa has a smallvec feature but it doesn't work
    #[schema(value_type = Vec<(Enemy, u8)>)]
    Combat(SmallVec<[(Enemy, u8); 12]>),
    Boss(f32),
    BreakWall(f32),
    ShurikenBreak(f32),
    SentryBreak(f32),
    #[schema(no_recursion)]
    And(Vec<Requirement>),
    #[schema(no_recursion)]
    Or(Vec<Requirement>),
}

impl Requirement {
    pub fn and<I: IntoIterator<Item = Self>>(requirements: I) -> Self {
        let mut filtered = vec![];

        for requirement in requirements {
            match requirement {
                Self::Free => {}
                Self::Impossible => return Self::Impossible,
                Self::And(nested) => filtered.extend(nested),
                other => filtered.push(other),
            }
        }

        match filtered.len() {
            0 => Self::Free,
            1 => filtered.pop().unwrap(),
            _ => Self::And(filtered),
        }
    }

    pub fn or<I: IntoIterator<Item = Self>>(requirements: I) -> Self {
        let mut filtered = vec![];

        for requirement in requirements {
            match requirement {
                Self::Free => return Self::Free,
                Self::Impossible => {}
                Self::Or(nested) => filtered.extend(nested),
                other => filtered.push(other),
            }
        }

        match filtered.len() {
            0 => Self::Impossible,
            1 => filtered.pop().unwrap(),
            _ => Self::Or(filtered),
        }
    }

    pub fn logical_eq(&self, other: &Self) -> bool {
        // TODO could prob optimize this significantly
        matches!(self.logical_cmp(other), Some(Ordering::Equal))
    }

    pub fn logical_ne(&self, other: &Self) -> bool {
        !self.logical_eq(other)
    }

    pub fn logical_lt(&self, other: &Self) -> bool {
        matches!(self.logical_cmp(other), Some(Ordering::Less))
    }

    pub fn logical_le(&self, other: &Self) -> bool {
        matches!(
            self.logical_cmp(other),
            Some(Ordering::Less | Ordering::Equal)
        )
    }

    pub fn logical_gt(&self, other: &Self) -> bool {
        matches!(self.logical_cmp(other), Some(Ordering::Greater))
    }

    pub fn logical_ge(&self, other: &Self) -> bool {
        matches!(
            self.logical_cmp(other),
            Some(Ordering::Greater | Ordering::Equal)
        )
    }

    // TODO could use this for redundancy filtering in the optimizer?
    /// Compares two `Requirements` by their logical meaning
    ///
    /// - `None` means the requirements are unrelated
    /// - `Some(Ordering::Less)` means `self` is strictly more easily met than `other`
    /// - `Some(Ordering::Equal)` means `self` and `other` are always met together
    /// - `Some(Ordering::Greater)` means `other` is strictly more easily met than `self`
    ///
    /// Note that some amount of normalization is expected. For example
    /// `(DoubleJump & (Dash & Launch))` will not be equal to `(DoubleJump & Dash & Launch)`.
    /// And and Or requirements should be flattened for proper results.
    /// This function also won't venture into the depths of OR redundancy checking.
    pub fn logical_cmp(&self, other: &Self) -> Option<Ordering> {
        fn cmp_ordered<A, B, F>(a: A, b: B, mut f: F) -> Option<Ordering>
        where
            A: IntoIterator,
            B: IntoIterator,
            F: FnMut(A::Item, B::Item) -> Option<Ordering>,
        {
            let mut a_iter = a.into_iter();
            let mut b_iter = b.into_iter();

            let mut ordering = Ordering::Equal;

            for (a_item, b_item) in iter::zip(&mut a_iter, &mut b_iter) {
                ordering = ordering.partial_then(f(a_item, b_item)?)?;
            }

            ordering.partial_then(a_iter.count().cmp(&b_iter.count()))
        }

        /// Compare a chain of requirements where order doesn't matter.
        ///
        /// Specifically that's non-orb and requirements and or requirements.
        ///
        /// We allow ourselves to ignore some edge cases here, for example
        /// Ore=4, Ore=2 can't be compared correctly to Ore=3 with this.
        /// As mentioned, we also don't check for redundancies across ORs.
        ///
        /// In effect, we only accept `None` or `Some(Equal)` orderings across the elements.
        fn cmp_unordered<'r, const IS_AND: bool>(
            a: impl IntoIterator<Item = &'r Requirement>,
            mut b: Vec<&Requirement>,
        ) -> Option<Ordering> {
            let mut ordering = Ordering::Equal;

            'outer: for a_item in a {
                let mut index = 0;
                while index < b.len() {
                    let b_item = b[index];

                    match a_item.logical_cmp(&b_item) {
                        Some(item_ordering) => {
                            if matches!(item_ordering, Ordering::Less | Ordering::Greater) {
                                ordering = ordering.partial_then(item_ordering)?;
                            }

                            b.swap_remove(index);
                            // exists in b, continue onwards, no duplicates are assumed
                            continue 'outer;
                        }
                        None => index += 1,
                    }
                }

                // did not exist in b
                ordering = ordering.partial_then(if IS_AND {
                    Ordering::Greater
                } else {
                    Ordering::Less
                })?;
            }

            if b.is_empty() {
                // everything matched
                Some(ordering)
            } else {
                // something did not exist in a
                ordering.partial_then(if IS_AND {
                    Ordering::Less
                } else {
                    Ordering::Greater
                })
            }
        }

        fn cmp_many_to_one(
            many: &[Requirement],
            one: &Requirement,
            cmp: fn(&Requirement, &Requirement) -> bool,
            ord: Ordering,
        ) -> Option<Ordering> {
            many.iter()
                .any(|many_item| cmp(many_item, one))
                .then_some(ord)
        }

        match (self, other) {
            (Self::Free, Self::Free) | (Self::Impossible, Self::Impossible) => {
                Some(Ordering::Equal)
            }
            (Self::Free, _) | (_, Self::Impossible) => Some(Ordering::Less),
            (_, Self::Free) | (Self::Impossible, _) => Some(Ordering::Greater),
            (Self::Difficulty(a), Self::Difficulty(b)) => Some(a.cmp(b)),
            (Self::EnergySkill(a, a_amount), Self::EnergySkill(b, b_amount)) if a == b => {
                Some(a_amount.total_cmp(b_amount))
            }
            (Self::SpiritLight(a), Self::SpiritLight(b))
            | (Self::GorlekOre(a), Self::GorlekOre(b))
            | (Self::Keystone(a), Self::Keystone(b)) => Some(a.cmp(b)),
            (Self::Damage(a), Self::Damage(b))
            | (Self::Danger(a), Self::Danger(b))
            | (Self::Boss(a), Self::Boss(b))
            | (Self::BreakWall(a), Self::BreakWall(b))
            | (Self::ShurikenBreak(a), Self::ShurikenBreak(b))
            | (Self::SentryBreak(a), Self::SentryBreak(b)) => Some(a.total_cmp(b)),
            (Self::Combat(a), Self::Combat(b)) => {
                cmp_ordered(a, b, |(a_enemy, a_amount), (b_enemy, b_amount)| {
                    (a_enemy == b_enemy).then(|| a_amount.cmp(b_amount))
                })
            }
            (Self::And(a), Self::And(b)) => {
                fn partition_orbs<'r, 'v>(
                    ands: &'r [Requirement],
                    non_orb_ands: &'v mut Vec<&'r Requirement>,
                ) -> impl Iterator<Item = &'r Requirement> + use<'r, 'v> {
                    ands.iter().filter(|&and| {
                        let changes_orbs = and.changes_orbs();

                        if !changes_orbs {
                            non_orb_ands.push(and);
                        }

                        changes_orbs
                    })
                }

                let mut a_non_orb_ands = Vec::new();
                let a_orb_ands = partition_orbs(a, &mut a_non_orb_ands);
                let mut b_non_orb_ands = Vec::new();
                let b_orb_ands = partition_orbs(b, &mut b_non_orb_ands);

                cmp_ordered(a_orb_ands, b_orb_ands, Requirement::logical_cmp)?
                    .partial_then(cmp_unordered::<true>(a_non_orb_ands, b_non_orb_ands)?)
            }
            (Self::Or(a), Self::Or(b)) => cmp_unordered::<false>(a, b.iter().collect()),
            // absurd edge cases like comparing Ore=4, Ore=2 with Ore=3 are ignored here as well
            (Self::And(many), one) | (one, Self::Or(many)) => {
                cmp_many_to_one(many, one, Requirement::logical_le, Ordering::Greater)
            }
            (one, Self::And(many)) | (Self::Or(many), one) => {
                cmp_many_to_one(many, one, Requirement::logical_ge, Ordering::Less)
            }
            // TODO eq basically redoes the whole matching, maybe we should manually add all the other branches here?
            _ if self == other => Some(Ordering::Equal),
            _ => None,
        }
    }

    pub(super) fn changes_orbs(&self) -> bool {
        self.orb_change_kind().is_some()
    }

    pub(super) fn orb_change_kind(&self) -> Option<OrbChangeKind> {
        match self {
            Self::Damage(_) | Self::Danger(_) => Some(OrbChangeKind::Health),
            Self::EnergySkill(_, _) | Self::NonConsumingEnergySkill(_) => {
                Some(OrbChangeKind::Energy)
            }
            Self::Combat(_)
            | Self::Boss(_)
            | Self::BreakWall(_)
            | Self::ShurikenBreak(_)
            | Self::SentryBreak(_) => Some(OrbChangeKind::Destroy),
            Self::And(requirements) | Self::Or(requirements) => {
                requirements.iter().filter_map(Self::orb_change_kind).max()
            }
            _ => None,
        }
    }
}

impl Display for Requirement {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Free => write!(f, "free"),
            Self::Impossible => write!(f, "Impossible"),
            Self::Difficulty(difficulty) => difficulty.fmt(f),
            Self::NormalGameDifficulty => write!(f, "NormalGameDifficulty"),
            Self::Trick(trick) => trick.fmt(f),
            Self::Skill(skill) => skill.fmt(f),
            Self::EnergySkill(skill, amount) => write!(f, "{skill}={amount}"),
            Self::NonConsumingEnergySkill(skill) => write!(f, "NonConsuming{skill}"),
            Self::SpiritLight(amount) => write!(f, "SpiritLight={amount}"),
            Self::GorlekOre(amount) => write!(f, "GorlekOre={amount}"),
            Self::Keystone(amount) => write!(f, "Keystone={amount}"),
            Self::Shard(shard) => shard.fmt(f),
            Self::Teleporter(teleporter) => teleporter.fmt(f),
            Self::Water => write!(f, "Water"),
            Self::State(state) => write!(f, "{{{state}}}"),
            Self::Damage(amount) => write!(f, "Damage={amount}"),
            Self::Danger(amount) => write!(f, "Danger={amount}"),
            Self::Combat(enemies) => write!(
                f,
                "Combat={}",
                enemies
                    .iter()
                    .format_with("+", |(enemy, amount), f| if *amount == 1 {
                        f(&enemy)
                    } else {
                        f(&format_args!("{amount}x{enemy}"))
                    })
            ),
            Self::Boss(health) => write!(f, "Boss={health}"),
            Self::BreakWall(health) => write!(f, "BreakWall={health}"),
            Self::ShurikenBreak(health) => write!(f, "ShurikenBreak={health}"),
            Self::SentryBreak(health) => write!(f, "SentryBreak={health}"),
            Self::And(ands) => write!(f, "({})", ands.iter().format(" & ")),
            Self::Or(ors) => write!(f, "({})", ors.iter().format(" | ")),
        }
    }
}

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum OrbChangeKind {
    Health,
    Energy,
    Destroy,
}

#[derive(Debug, PartialEq, Eq, Hash, Clone, Copy, Serialize, ToSchema, EnumString, Display)]
pub enum Enemy {
    Mantis,
    Slug,
    WeakSlug,
    BombSlug,
    CorruptSlug,
    SneezeSlug,
    ShieldSlug,
    Lizard,
    Bat,
    Hornbug,
    Skeeto,
    SmallSkeeto,
    Bee,
    Nest,
    Crab,
    SpinCrab,
    Tentacle,
    Balloon,
    Miner,
    MaceMiner,
    ShieldMiner,
    CrystalMiner,
    ShieldCrystalMiner,
    Sandworm,
    Spiderling,
    EnergyRefill,
}

impl Enemy {
    pub const fn health(self) -> f32 {
        match self {
            Enemy::BombSlug | Enemy::CorruptSlug | Enemy::Balloon => 1.0,
            Enemy::SmallSkeeto => 8.0,
            Enemy::WeakSlug | Enemy::Spiderling => 12.0,
            Enemy::Slug => 13.0,
            Enemy::Skeeto | Enemy::Sandworm | Enemy::Tentacle => 20.0,
            Enemy::ShieldSlug | Enemy::Lizard | Enemy::Bee => 24.0,
            Enemy::Nest => 25.0,
            Enemy::Mantis | Enemy::SneezeSlug | Enemy::Bat | Enemy::Crab | Enemy::SpinCrab => 32.0,
            Enemy::Hornbug | Enemy::Miner => 40.0,
            Enemy::ShieldCrystalMiner => 50.0,
            Enemy::MaceMiner | Enemy::ShieldMiner => 60.0,
            Enemy::CrystalMiner => 80.0,
            Enemy::EnergyRefill => 0.0,
        }
    }

    pub const fn shielded(self) -> bool {
        matches!(
            self,
            Enemy::Hornbug | Enemy::ShieldSlug | Enemy::ShieldMiner | Enemy::ShieldCrystalMiner
        )
    }

    pub const fn armored(self) -> bool {
        matches!(self, Enemy::Tentacle)
    }

    pub const fn aerial(self) -> bool {
        // whether we consider the enemy flying for movement restriction purposes
        matches!(
            self,
            Enemy::Bat
                | Enemy::Skeeto
                | Enemy::SmallSkeeto
                | Enemy::Bee
                | Enemy::Nest
                | Enemy::Tentacle
        )
    }

    pub const fn flying(self) -> bool {
        // whether the game considers the enemy flying for wingclip
        matches!(self, Enemy::Skeeto | Enemy::SmallSkeeto | Enemy::Bee)
    }

    pub const fn ranged(self) -> bool {
        // whether you need a ranged weapon
        matches!(
            self,
            Enemy::BombSlug | Enemy::CorruptSlug | Enemy::Balloon | Enemy::Bat
        )
    }

    pub const fn dangerous(self) -> bool {
        matches!(
            self,
            Enemy::SneezeSlug
                | Enemy::Hornbug
                | Enemy::Crab
                | Enemy::SpinCrab
                | Enemy::Miner
                | Enemy::MaceMiner
                | Enemy::ShieldMiner
                | Enemy::CrystalMiner
                | Enemy::ShieldCrystalMiner
        )
    }
}
