name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Test Seedgen
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
# TODO maybe a test to check linux and windows generate the same seeds?
